---
    #SLURM dependences 
    - name: update repositories cache and yum install slurm dependences in REL systems
      yum: name=readline-devel,openssl,openssl-devel,munge-devel,pam-devel,perl-ExtUtils-MakeMaker,gcc,make,rpm-build,perl-DBI,psmisc,mariadb-devel

    - name: Install perl-Switch in CentOS 7
      yum: name=perl-Switch
      when: ansible_distribution_major_version == "7"

    - name: download SLURM package
      get_url: url=https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2 dest=/tmp/slurm-{{ slurm_version }}.tar.bz2

    - name: build rpm slurm package
      command: rpmbuild -ta slurm-{{ slurm_version }}.tar.bz2 chdir=/tmp creates=/root/rpmbuild/RPMS/x86_64/slurm-{{ slurm_version }}-1.el7.centos.x86_64.rpm

    - name: install rpm slurm package
      command: rpm -Uvh --force ~/rpmbuild/RPMS/x86_64/*.rpm chdir=/tmp creates=/etc/init.d/slurm

    - set_fact: SLURM_CONF="/etc/slurm/slurm.conf"  SLURM_SERVICE="slurm"

    - set_fact: SLURM_SERVICE="slurmd"
      when: ansible_os_family == "RedHat" and slurm_type_of_node == "worker"

    - set_fact: SLURM_SERVICE="slurmctld"
      when: ansible_os_family == "RedHat" and slurm_type_of_node == "controller"
  
    - name: create slurm user and group
      user: name=slurm shell=/bin/bash system=yes

    - name: create folders used by SLURM and set slurm owner
      file: path={{item}} state=directory owner=slurm group=slurm
      with_items:
         - /var/spool/slurm
         - /var/log/slurm
         - /var/slurm/checkpoint
         - /etc/slurm

    - name: Disable firewall in CentOS 7
      service: name=firewalld state=stopped enabled=False
      when: ansible_distribution_major_version == "7"
      ignore_errors: yes
